repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: name-tests-test

  - repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: 1.0.4
    hooks:
      - id: python-import-sorter
        args: [ '--silent-overwrite' ]


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
