name: Worker CI/CD
on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: ./docker/dockerize.sh build

  cd:
    runs-on: ubuntu-latest
    steps:
      - run: docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: ./docker/dockerize.sh push
      - run: ./docker/dockerize.sh clean
